New route
ElizabethArr/pokemons_app pull request #3
Opened 2023-12-19 17:24 UTC by ElizabethArr

Cambios PR

2023-12-20 15:55 UTC, josuemonroy2023 requested changes

2023-12-20 15:55 UTC, josuemonroy2023 commented on src/components/MediaCardPoke.tsx
> +  const [customState, setCustomState] = useState('10');
Veo que más adelante conviertes esto a un integer, no sería mejor que desde un inicio fuera un número?

2023-12-20 15:55 UTC, josuemonroy2023 commented on src/components/NewHook.tsx
> +const NewHook = (initialValue:any) => {
Lo ideal aquí sería que si sabes que va a ser un número lo único que va a recibir el hook el tipo de valor fuera numérico. Y así también eliminar la conversión en el estado.

2023-12-20 15:55 UTC, josuemonroy2023 commented on src/components/NewHook.tsx
> +// useCustomHook.js
El nombre del hook debería de ser más descriptivo de la acción o la intención.

2023-12-27 20:15 UTC, josuemonroy2023 commented on src/components/MediaCardPoke.tsx
> +    fetchPokemonData(parseInt(customState.toString(), 10));
Si sabemos que customState es un número no hay necesidad de convertirlo a un string para luego regresarlo a un int.

2024-01-03 17:46 UTC, josuemonroy2023 approved these changes

2024-01-03 17:59 UTC, ElizabethArr commented
Listo y aprobado el PR.

2024-01-03 17:59 UTC, closed without merging